### ISSUE TITLE
Finishes not updating

### ISSUE THREAD

**Issue by tomnueske** [JOKeRiino/schweineaim-remixed#1]
The spreadsheet was updated to 30 fins for Roeder but it seems that the googlescript doesnt grab the 30th fin. As I can only see the URI to call the script and not the script itself i cant provide a solution for this issue. It would be nice to have this one fixed as the script is used for the !finishes command in the livestream chat from Roeder.

**Comment by JOKeRiino** [comment]
Hey Tom, I had to build a new google sheet as the data structure on the KX2 sheet was not sufficient for the project (as I cannot access links that are set as hyperlinks). So all the changes have to be made manually by me. I guess there are only two solutions for this problem: 1) Someone messages me on twitter so I can update my spreadsheet asap. 2) Someone from the mod team gets access to my file and updates it along with the KX2 sheet. Anyway, I would be honored to be featured on the !finish command! If you want to shoot me a message on Twitter (@riino_dev) or Twitch (riinoLive) to talk things through (maybe on discord) feel free to do so!

**Comment by tomnueske** [comment]
I just made the script myself now. Will close this issue.
